[package]
name = "rust-implementations"
version = "0.1.0"
authors = ["Shaun Luttin <admin@shaunluttin.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
